# Minimal golangci-lint configuration - just the essentials
run:
  timeout: 5m
  go: "1.23"

linters:
  disable-all: true
  enable:
    - gofmt # Just check formatting
    - goimports # Just check imports
    - errcheck # Just check errors

linters-settings:
  goimports:
    local-prefixes: velocity

issues:
  max-issues-per-linter: 20
  max-same-issues: 5
