run:
  timeout: 5m
  go: "1.23"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  golint:
    min-confidence: 0.8

  gofmt:
    simplify: true

  goimports:
    local-prefixes: velocity

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck # Check for unchecked errors
    - gofmt # Check formatting
    - goimports # Check imports
    - govet # Go vet
    - ineffassign # Detect ineffectual assignments
    - misspell # Detect misspellings
    - typecheck # Type checking
    - unused # Detect unused code
    - deadcode # Detect dead code
    - structcheck # Find unused struct fields
    - varcheck # Find unused global variables and constants

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
