# Velocity Gateway - Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
        if_not_found: success
        only_pulls: false

    patch:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error
        if_not_found: success
        only_pulls: true

  ignore:
    - "cmd/" # Main entry points don't need full coverage
    - "**/*_test.go" # Test files themselves
    - "**/testdata/**" # Test data directories
    - "examples/" # Example code
    - "scripts/" # Build scripts
    - "tools/" # Development tools

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

github_checks:
  annotations: true

flags:
  unittests:
    paths:
      - internal/
      - pkg/
    carryforward: true

  integration:
    paths:
      - tests/integration/
    carryforward: false
